version: "3.9"

services:

  # Create service with RabbitMQ.
  broker:
    image: rabbitmq:3-management-alpine
    container_name: crazy-candle-broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    restart: always

  mongo:
    image: mongo
    restart: always
    container_name: crazy-candle-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: development

  mongo-express:
    image: mongo-express
    container_name: crazy-candle-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: development
      ME_CONFIG_MONGODB_URL: mongodb://root:development@mongo:27017/

  generator:
    build:
      context: ./generator
    container_name: crazy-candle-generator
    command: sh -c "./wait && ./run"
    environment:
      WAIT_HOSTS: broker:5672
      WAIT_TIMEOUT: 60
    depends_on:
      - broker

  api:
    build:
      context: ./api
    container_name: crazy-candle-api
    command: sh -c "./wait && ./server"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: broker:5672, mongo:27017 
      WAIT_TIMEOUT: 60
    depends_on:
      - generator
      - mongo


  web:
    build:
      context: ./web
    container_name: crazy-candle-web
    command: sh -c "./wait && nginx -g 'daemon off;'"
    ports:
      - 80:80
    environment:
      WAIT_HOSTS: api:8080
    depends_on:
        - api