@startuml crazy candle simulator

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddRelTag("async", $lineStyle = DashedLine())

title "Crazy Candle Container Diagram"


Person(client, "Client")



System_Boundary(boundary, "Crazy candle system") {
    Container(web_container, "Web page", "HTML/CSS/JS", "Allows client view real time candle graph")
    Container(api_container, "Candle API", "Go", "Provides real time candle values")
    Container(generator_container, "Candle Generator", "Go", "Generates random candle values")
    ContainerDb(database, "Candle Database", "Mongo", "Stores candle history")
}

Rel(client, web_container, "Uses", "HTTPS", "Views real time crazy candle graph")

Rel(web_container, api_container, "Uses", "HTTPS", "Get initial informations")
Rel(web_container, api_container, "Uses", "Socket/TCP", "Get real time informations", $tags = "async")

Rel(api_container, generator_container, "Get generated candle values", "RabitMQ", $tags = "async")
Rel(api_container, database, "Stores/Gets candle history", "MongoDb Driver",)
@enduml