@startuml crazy candle simulator

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddRelTag("async", $lineStyle = DashedLine())

title "Crazy Candle Container Diagram"


Person(client, "Client")



System_Boundary(boundary, "Crazy candle system") {
    Container(web_container, "Web page", "React", "Allows client view candle graph and program automatic buy/sell operations")
    Container(api_container, "Candle API", "Go", "Provides real time candle values and functionality to manage buy/sell operations")
    Container(generator_container, "Candle Generator", "Go", "Generates random candle values")
    ContainerDb(database, "Candle Database", "Mongo", "Stores candle values, buy/sell optiosn and transactions history")
}

Rel(client, web_container, "Uses", "HTTPS", "Views real time crazy candle graph and program buy/sell operations")

Rel(web_container, api_container, "Uses", "HTTPS", "Register buy/sell operations")
Rel(web_container, api_container, "Uses", "Socket/TCP", "Get real time informations")

Rel(api_container, generator_container, "Get candle values", "RabitMQ", $tags = "async")
Rel(api_container, database, "Uses", "MongoDb Driver",)
@enduml